server:
  port: 8080
  servlet:
    context-path: /prediction

spring:
  servlet:
    multipart:
      max-file-size=50MB
      max-request-size=50MB
  application:
    name: prediction-service

# ML API Configuration - новая модель
ml:
  api:
    host: ${ML_API_HOST:109.73.196.162}
    port: ${ML_API_PORT:80}
    endpoint: ${ML_API_ENDPOINT:/model/damage-detection/analyze}
    timeout: ${ML_API_TIMEOUT:60000}

# YOLO API Configuration
yolo:
  api:
    url: ${YOLO_API_URL:https://serverless.roboflow.com/avdaafic/2}
    key: ${YOLO_API_KEY:5NBeshFE4AHBqkZhm384}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.predictionservice: INFO
    org.springdoc: INFO
    root: INFO 